### ISSUE TITLE
Failed to install the following Android SDK packages as some licences have not been accepted

### ISSUE THREAD

**Issue by g123k** [bitrise-steplib/bitrise-step-flutter-build#25]
Hello,

I am currently using Flutter beta and the step fails with this error:

```
Could not determine the dependencies of task ':app:compileInternalReleaseJavaWithJavac'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;28.0.3 Android SDK Build-Tools 28.0.3
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
```

How can I fix this?

**Comment by cmengler** [comment]
I had the same problem -- in the interim I've added this step above `flutter-build`:

```yaml
- script@1.1.5:
    inputs:
    - content: |-
        #!/usr/bin/env bash
        yes | $ANDROID_HOME/tools/bin/sdkmanager --install "build-tools;28.0.3"
```
